"""add technician to incidence

Revision ID: 05aa4abcadcb
Revises: a48aa3221361
Create Date: 2026-05-25 12:09:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05aa4abcadcb'
down_revision = 'a48aa3221361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technician_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_incidence_technician_id', 'user', ['technician_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidence', schema=None) as batch_op:
        batch_op.drop_constraint('fk_incidence_technician_id', type_='foreignkey')
        batch_op.drop_column('technician_id')

    # ### end Alembic commands ###
