"""add pin_code and property_id

Revision ID: 2782a8e0b300
Revises: b0654e93412d
Create Date: 2026-06-04 10:43:55.412151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2782a8e0b300'
down_revision = 'b0654e93412d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_code', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_property_pin_code', ['pin_code'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_property_id_property', 'property', ['property_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_property_id_property', type_='foreignkey')
        batch_op.drop_column('property_id')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_constraint('uq_property_pin_code', type_='unique')
        batch_op.drop_column('pin_code')

    # ### end Alembic commands ###
