"""add phone fields to user

Revision ID: b0654e93412d
Revises: be6472fd64ed
Create Date: 2026-05-29 11:26:06.718327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0654e93412d'
down_revision = 'be6472fd64ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_prefix', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('phone_prefix')

    # ### end Alembic commands ###
