"""add_asset_model

Revision ID: be6472fd64ed
Revises: 05aa4abcadcb
Create Date: 2026-05-27 10:38:37.085060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6472fd64ed'
down_revision = '05aa4abcadcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_incidence_asset_id', 'asset', ['asset_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidence', schema=None) as batch_op:
        batch_op.drop_constraint('fk_incidence_asset_id', type_='foreignkey')
        batch_op.drop_column('asset_id')

    op.drop_table('asset')
    # ### end Alembic commands ###
